name: Django CI Pipeline

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r myproject/requirements.txt
          
      - name: Run Django checks
        run: |
          cd myproject
          python manage.py check --deploy
          python manage.py collectstatic --noinput
          
      - name: Run tests
        run: |
          cd myproject
          python manage.py test myproject.tests.test
          
      - name: Verify server
        if: success()
        run: |
          cd myproject
          python manage.py runserver &
          sleep 5
          curl -s http://localhost:8000 | grep "Django"