name: Django CI Pipeline

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r myproject/requirements.txt
          pip install gunicorn  # Install gunicorn for running the server
          pip install flask  # Required for Ngrok tunnel

      - name: Apply Migrations and Collect Static Files
        run: |
          cd myproject
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Start Django Server in Background
        run: |
          cd myproject
          gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 &

      - name: Install and Start Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok http 8000 > /dev/null &  # Start Ngrok and expose port 8000

      - name: Get Ngrok URL
        run: |
          sleep 5  # Wait for Ngrok to initialize
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
